# Generated by Django 6.0.3 on 2026-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_apikey_encrypted_key_to_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Set when the key is revoked. Authentication rejects keys with a non-null revoked_at even if the row is otherwise active. Soft-revocation is preferred over delete so audit trails stay intact.', null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(condition=models.Q(('is_active', True), ('revoked_at__isnull', True)), fields=['prefix'], name='apikey_active_lookup'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.CheckConstraint(condition=models.Q(('updated_at__gte', models.F('created_at'))), name='accounts_apikey_updated_at_gte_created_at'),
        ),
    ]
