#!/usr/bin/env python3
"""Dump every env-var read by ``config/settings/base.py`` as a markdown table.

Django settings aren't pydantic, so there is no class introspection to
hang the schema off. Instead, this script AST-walks
``config/settings/base.py`` and lists every call to
:func:`_env_int`, :func:`_env_bool`, or :func:`os.getenv` — those are
the documented contract points for environment configuration. The
emitted table mirrors the matrix already maintained by hand in
``docs/configuration.md``.

The same script doubles as a drift guard in ``--check`` mode: it diffs
its rendered table against the auto-block in ``docs/configuration.md``
and exits non-zero on mismatch so a forgotten doc update fails CI
rather than silently rotting.

Run modes::

    python scripts/dump_settings_schema.py             # print to stdout
    python scripts/dump_settings_schema.py --write     # patch docs/configuration.md
    python scripts/dump_settings_schema.py --check     # exit 1 if docs are stale

Hand-written prose around the table is preserved verbatim by the
``BEGIN AUTO`` / ``END AUTO`` markers — add them once on first run.
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SETTINGS_PATH = ROOT / "config" / "settings" / "base.py"
DOC_PATH = ROOT / "docs" / "configuration.md"

BEGIN_MARKER = "<!-- BEGIN AUTO: env-vars table — generated by scripts/dump_settings_schema.py -->"
END_MARKER = "<!-- END AUTO -->"


@dataclass(frozen=True)
class EnvVar:
    name: str
    default: str
    typ: str
    line: int


def _literal(node: ast.AST) -> str | None:
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.JoinedStr):
        return "<f-string>"
    if isinstance(node, ast.BinOp):
        return "<expr>"
    if isinstance(node, ast.Call):
        return "<call>"
    if isinstance(node, ast.Name):
        return node.id
    return None


def _collect(tree: ast.Module) -> list[EnvVar]:
    found: dict[str, EnvVar] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if isinstance(func, ast.Name) and func.id in {"_env_int", "_env_bool"}:
            typ = "int" if func.id == "_env_int" else "bool"
        elif (
            isinstance(func, ast.Attribute)
            and func.attr == "getenv"
            and isinstance(func.value, ast.Name)
            and func.value.id == "os"
        ):
            typ = "str"
        else:
            continue
        if not node.args:
            continue
        name_node = node.args[0]
        if not isinstance(name_node, ast.Constant) or not isinstance(name_node.value, str):
            continue
        name = name_node.value
        default = "—"
        if len(node.args) >= 2:
            default = _literal(node.args[1]) or "<expr>"
        # Same env var may appear in multiple environments; keep first
        # occurrence in base.py to avoid duplicate rows.
        if name not in found:
            found[name] = EnvVar(name=name, default=default, typ=typ, line=node.lineno)
    return sorted(found.values(), key=lambda v: v.name)


def render_table(vars_: list[EnvVar]) -> str:
    lines = [
        BEGIN_MARKER,
        "",
        "| Env var | Type | Default | Source |",
        "|---|---|---|---|",
    ]
    for v in vars_:
        lines.append(
            f"| `{v.name}` | `{v.typ}` | {v.default} | `config/settings/base.py:{v.line}` |"
        )
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def render_full_doc(table: str) -> str:
    if DOC_PATH.exists():
        existing = DOC_PATH.read_text(encoding="utf-8")
        if BEGIN_MARKER in existing and END_MARKER in existing:
            before, _, rest = existing.partition(BEGIN_MARKER)
            _, _, after = rest.partition(END_MARKER)
            return f"{before}{table}{after}"
        # No markers yet — append the table at the end so the operator
        # can move it into place on the next edit.
        return existing.rstrip() + "\n\n" + table + "\n"
    header = (
        "# Configuration\n\n"
        "Every environment variable read by `config/settings/base.py`.\n"
        "The table below is regenerated by\n"
        "`scripts/dump_settings_schema.py`. Do not hand-edit the rows\n"
        "between the `BEGIN AUTO` / `END AUTO` markers — run the script\n"
        "instead. Prose around the markers is preserved.\n\n"
    )
    return header + table + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="patch docs/configuration.md")
    group.add_argument("--check", action="store_true", help="exit 1 if docs are stale")
    args = parser.parse_args()

    tree = ast.parse(SETTINGS_PATH.read_text(encoding="utf-8"), filename=str(SETTINGS_PATH))
    vars_ = _collect(tree)
    table = render_table(vars_)

    if args.write:
        rendered = render_full_doc(table)
        DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        DOC_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {DOC_PATH.relative_to(ROOT)} ({len(vars_)} env vars)")
        return 0

    if args.check:
        if not DOC_PATH.exists():
            print(f"{DOC_PATH.relative_to(ROOT)} missing; run --write", file=sys.stderr)
            return 1
        current = DOC_PATH.read_text(encoding="utf-8")
        rendered = render_full_doc(table)
        if current != rendered:
            print(
                f"{DOC_PATH.relative_to(ROOT)} is stale; run "
                "`python scripts/dump_settings_schema.py --write` and commit.",
                file=sys.stderr,
            )
            return 1
        return 0

    print(table)
    return 0


if __name__ == "__main__":
    sys.exit(main())
