# Generated by Django 6.0.3 on 2026-05-29 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('service_name', models.CharField(max_length=128)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('method', models.CharField(max_length=16)),
                ('url', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ttl_expires_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['service_name', 'created_at'], name='api_logs_service_bceee2_idx'), models.Index(fields=['direction', 'created_at'], name='api_logs_directi_9f86f5_idx')],
            },
        ),
    ]
